server.port=8083
spring.application.name=registration-service

# Database configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/registration_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=quyetdragon
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Course Service URL for internal communications
course-service.base-url=http://localhost:8082

# JWT Secret (Dung chung cho ca he thong)
jwt.secret=CRS-Microservices-Secret-Key-Nam-3-Hoc-Ky-2026-Doi-Trong-Thuc-Te
